####################################
# Automatically generated by SMake #
# https://github.com/kala13x/smake #
####################################

CFLAGS = -g -O2 -Wall -Isrc
LIBS = -lpthread
NAME = libslog.a
ODIR = lib
OBJ = o

ifeq ($(UNAME_S),Darwin)
CFLAGS += -DDARWIN
endif

OBJS = slog.$(OBJ)
OBJECTS = $(patsubst %,$(ODIR)/%,$(OBJS))
HEADERS = /usr/local/include
INSTALL = /usr/local/lib
VPATH = src

.c.$(OBJ):
	@test -d $(ODIR) || mkdir $(ODIR)
	$(CC) $(CFLAGS) -c -o $(ODIR)/$@ $< $(LIBS)

$(NAME):$(OBJS)
	$(AR) rcs -o $(ODIR)/$(NAME) $(OBJECTS)
	@test -d $(BUILD) || mkdir $(BUILD)

.PHONY: install
install:
	@test -d $(INSTALL) || mkdir $(INSTALL)
	@install -m 0755 $(ODIR)/$(NAME) $(INSTALL)/
	@test -d $(HEADERS) || mkdir $(HEADERS)
	@install -m 0755 $(VPATH)/*.h $(HEADERS)/

.PHONY: clean
clean:
	$(RM) $(ODIR)/$(NAME) $(OBJECTS)
