name: SLog CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: sudo apt-get install -y build-essential valgrind cmake

      - name: Install slog
        run: cmake . && make && sudo make install

      - name: Compile Tests
        run: gcc -o test_slog tests.c -lslog -g

      - name: Compile Example
        run: gcc -o slog_example example.c -lslog -g

      - name: Run Valgrind Memory Check With Tests
        run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./test_slog

      - name: Run Valgrind Memory Check With Example
        run: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --error-exitcode=1 ./slog_example